# Generated by Django 3.2.25 on 2024-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
