# Generated by Django 3.2.25 on 2024-12-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20241127_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='game',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
    ]
